apiVersion: storage.k8s.io/v1
kind: PersistentVolumeClaim
metadata: 
  name: block-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod 
metadata:
  name: nginx-blockstorage
spec:
  containers:
    - name: app-container
      image: nginx
      volumeMounts:
      - name: block-volume 
        mountPath: "/etc/nginx"
  volumes:
    - name: block-volume
      persistentVolumeClaim:
        claimName: block-pvc
