apiVersion: storage.k8s.io/v1
kind: PersistentVolumeClaim
metadata: 
  name: cephfs-pvc
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod 
metadata:
  name: nginx-filesystemstorage
spec:
  containers:
    - name: app-container
      image: nginx
      volumeMounts:
      - name: block-volume 
        mountPath: "/etc/nginx"
  volumes:
    - name: filesystem-volume
      persistentVolumeClaim:
        claimName: cephfs-pvc
